### ISSUE TITLE
[FEATURE]: Update ABI

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-cli#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

https://github.com/koinos/koinos-cli/blob/9f0069d149f0c8d736e7e4093685094ce3637a39/internal/cli/abi.go#L86-L92

* use `entry_point` as uint32 instead of string
* use underscore in `read_only`

**Comment by roaminro** [comment]
@joticajulian @mvandeberg @sgerbino 
I think we need to harmonize the ABI definition, it looks like the ABI for the CLI was updated to use `entry-point` and `read-only` whereas the ABI for Koilib was updated to use `entry_point` and `read_only`
