### ISSUE TITLE
[BUG]: CLI transfer verb doesn't parse/validate target address

### ISSUE THREAD

**Issue by koignettt** [koinos/koinos-cli#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

From the CLI
- transfer 0.1 15UWU3BYRRJTA5I2U9BR19MDGFQBC7Z2RN
  - Note the casing of the address. The receiving targeted address was 15uWu3bYRrJta5i2U9br19mDGFqBc7z2rn. 

The transaction was successful, but the receiving address was unexpected. 15UWU3BYRRJTA5

https://koinosblocks.com/tx/0x1220108592bf3ec2e86f5748791e3774db0d34933ceb4d1ab994e554227c2c45f7ef

It looks like there are a few issues. Please split and reassign if they pass triage.
1. The operation in the call contract uses the bad receiving address. I didn't verify the transaction args, but perhaps the CLI should validate and reject invalid addresses.
2. The transfer event shows that 15UWU3BYRRJTA5 should have received TKOIN. The sending address was decremented correctly, but the receiving account only received MANA? It difficult to tell if this is a UI bug in the explorer or if it's an actual error where MANA was recorded but the TKOIN was not.
- https://koinosblocks.com/address/15UWU3BYRRJTA5
3. It's odd that the blockchain even accepts an address with this format. Do accounts not use a well known algorithm and checkum? It seems like you can transfer TKOIN to a bunch of odd address string.
- transfer 0.3 somewhere
- https://koinosblocks.com/tx/0x1220419647e106ab20332d37629674dae3745911902a43a773276ae6611da276dc02
- https://koinosblocks.com/address/somewhere

### Expected behavior

The addresses should follow a well known format, be checksumed (to avoid mistakes via typos) and be validated anywhere its used.

### Environment

```markdown
- OS:
```

**Comment by mvandeberg** [comment]
Replaced by #183 (copying original report for clarity)
