### ISSUE TITLE
[FEATURE]: Balance command should validate that address is in correct format

### ISSUE THREAD

**Issue by jredbeard** [koinos/koinos-cli#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Currently when checking the balance of an address it is not validated to be in the proper format.

As far as I understand, it should validate that the address is to the P2PKH (original bitcoin spec, starts with 1, 34 characters, etc)

Example:

![image](https://user-images.githubusercontent.com/23157604/200359183-633e7412-5467-4858-ac65-67fce066d7de.png)

**Comment by mvandeberg** [comment]
Handled by #183
