### ISSUE TITLE
[FEATURE]: Add a `.koinosrc.testnet` file with defaults for testnet

### ISSUE THREAD

**Issue by jredbeard** [koinos/koinos-cli#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

As a developer I would like to have an example `.koinosrc.testnet` file in the repo that contains the harbinger testnet API endpoint and the correct contract addresses for the testnet so that I don't have to hunt for them elsewhere.

It may also be useful to document this in the `README`

**Comment by lukemwillis** [comment]
Here's an alternate approach at solving the same problem: https://github.com/koinos/koinos-cli/issues/187 -- either is fine with me.

**Comment by jredbeard** [comment]
> Here's an alternate approach at solving the same problem: #187 -- either is fine with me.

Yep I like that too... especially if it becomes part of #157

**Comment by lukemwillis** [comment]
That would certainly enhance #157 -- having mainnet & testnet just work out of the box would be killer.

**Comment by sgerbino** [comment]
Let's prefer the solution on #187.

**Comment by jredbeard** [comment]
Agree sgtm
